/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const JobType = IDL.Variant({
  'remote' : IDL.Null,
  'contract' : IDL.Null,
  'partTime' : IDL.Null,
  'fullTime' : IDL.Null,
});
export const JobStatus = IDL.Variant({
  'closed' : IDL.Null,
  'open' : IDL.Null,
});
export const JobListing = IDL.Record({
  'id' : IDL.Nat,
  'status' : JobStatus,
  'title' : IDL.Text,
  'jobType' : JobType,
  'postedDate' : IDL.Int,
  'description' : IDL.Text,
  'company' : IDL.Text,
  'salaryRange' : IDL.Text,
  'requirements' : IDL.Text,
  'location' : IDL.Text,
});
export const ApplicationStatus = IDL.Variant({
  'pending' : IDL.Null,
  'rejected' : IDL.Null,
  'reviewed' : IDL.Null,
  'accepted' : IDL.Null,
});
export const JobApplication = IDL.Record({
  'status' : ApplicationStatus,
  'applicant' : IDL.Principal,
  'jobId' : IDL.Nat,
  'coverLetter' : IDL.Text,
  'appliedDate' : IDL.Int,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'name' : IDL.Text,
  'role' : UserRole,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'applyForJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createJobListing' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
      [IDL.Nat],
      [],
    ),
  'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
  'filterByJobType' : IDL.Func(
      [JobType],
      [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
      ['query'],
    ),
  'filterByLocation' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
      ['query'],
    ),
  'getAllJobListings' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
      ['query'],
    ),
  'getApplicantJobApplications' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getJobApplications' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(JobApplication)],
      ['query'],
    ),
  'getJobListing' : IDL.Func([IDL.Nat], [JobListing], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasUserApplied' : IDL.Func([IDL.Nat, IDL.Principal], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchJobListings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
      ['query'],
    ),
  'setJobStatus' : IDL.Func([IDL.Nat, JobStatus], [], []),
  'updateApplicationStatus' : IDL.Func(
      [IDL.Nat, IDL.Principal, ApplicationStatus],
      [],
      [],
    ),
  'updateJobListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        JobType,
        JobStatus,
      ],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const JobType = IDL.Variant({
    'remote' : IDL.Null,
    'contract' : IDL.Null,
    'partTime' : IDL.Null,
    'fullTime' : IDL.Null,
  });
  const JobStatus = IDL.Variant({ 'closed' : IDL.Null, 'open' : IDL.Null });
  const JobListing = IDL.Record({
    'id' : IDL.Nat,
    'status' : JobStatus,
    'title' : IDL.Text,
    'jobType' : JobType,
    'postedDate' : IDL.Int,
    'description' : IDL.Text,
    'company' : IDL.Text,
    'salaryRange' : IDL.Text,
    'requirements' : IDL.Text,
    'location' : IDL.Text,
  });
  const ApplicationStatus = IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'reviewed' : IDL.Null,
    'accepted' : IDL.Null,
  });
  const JobApplication = IDL.Record({
    'status' : ApplicationStatus,
    'applicant' : IDL.Principal,
    'jobId' : IDL.Nat,
    'coverLetter' : IDL.Text,
    'appliedDate' : IDL.Int,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'name' : IDL.Text,
    'role' : UserRole,
    'email' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'applyForJob' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createJobListing' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text, JobType],
        [IDL.Nat],
        [],
      ),
    'deleteJobListing' : IDL.Func([IDL.Nat], [], []),
    'filterByJobType' : IDL.Func(
        [JobType],
        [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
        ['query'],
      ),
    'filterByLocation' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
        ['query'],
      ),
    'getAllJobListings' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
        ['query'],
      ),
    'getApplicantJobApplications' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getJobApplications' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(JobApplication)],
        ['query'],
      ),
    'getJobListing' : IDL.Func([IDL.Nat], [JobListing], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasUserApplied' : IDL.Func(
        [IDL.Nat, IDL.Principal],
        [IDL.Bool],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchJobListings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(IDL.Tuple(IDL.Nat, JobListing))],
        ['query'],
      ),
    'setJobStatus' : IDL.Func([IDL.Nat, JobStatus], [], []),
    'updateApplicationStatus' : IDL.Func(
        [IDL.Nat, IDL.Principal, ApplicationStatus],
        [],
        [],
      ),
    'updateJobListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          JobType,
          JobStatus,
        ],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };